name: Update Data
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

concurrency: ci-${{ github.ref }}

jobs:
  scan:
    name: Scan Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install xmllint
        run: sudo apt-get install -y unar ripgrep
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - run: cargo build --release
      - run: mkdir downloads/
#      - run: cargo run -- download-increment downloads/ > to-process.json
      - run: cargo run --release -- download-relative downloads/ 5 > to-process.json
      - run: cargo run --release -- process to-process.json
#      - uses: EndBug/add-and-commit@v9
#        with:
#          add: 'state.json'
#          # From https://github.community/t/github-actions-bot-email-address/17204/5
#          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
#          author_name: "commit-bot"
#          message: "Scheduled changelog data update from Github Actions"
#          push: true